use_frameworks!

target 'SLHomeModule_Example' do
  pod 'SLHomeModule', :path => '../'

  target 'SLHomeModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
